Add api purchase status / abort doc
pledgcorporate/ecard-doc pull request #45
Opened 2021-11-29 16:55 UTC by kmodry

2021-11-29 17:37 UTC, Romain-Ly requested changes

2021-11-29 17:37 UTC, Romain-Ly commented on docs/en/integration/api/purchase_link_generation.md
> +The signature parameter is describe as follow (example in python using jwt library):
is described ?

2021-11-29 17:37 UTC, Romain-Ly commented on docs/en/integration/api/purchase_link_generation.md
> +Once a purchase link is created, a status update can be checked using the following endpoint:
- the purchase status can be fetched/getted/checked 

- by using the following

2021-11-29 17:37 UTC, Romain-Ly commented on docs/en/integration/api/purchase_link_generation.md
> +| `status` | `string` | The current purchase status (amongst `OK`, `PENDING`, `FAILED`, `ABORTED`). |
`among`

2021-11-29 17:37 UTC, Romain-Ly commented on docs/en/integration/api/purchase_link_generation.md
> +In case of error, this endpoint will return a 400 http code along with an explanation.
Peut-etre donner la structure des données retournées.

2021-11-29 17:37 UTC, Romain-Ly commented on docs/en/integration/api/purchase_link_generation.md
> +`https://back.ecard.pledg.co/api/purchase_status/?signature=<signature> GET`
Moi je formaliserai comme dans une vrai API.
`GET /api/purchase_status/`

Et dans un endroit dire que c'est toujours vers `back.ecard.pledg.co`

2021-11-29 17:37 UTC, Romain-Ly commented on docs/en/integration/api/purchase_link_generation.md
> +This endpoint returns the following result:
Je pense qu'il faudrait donner de vrais exemple de la structure des données en cas d'erreur et de 200.
Voir https://api-docs.pledg.co/

2021-11-29 17:37 UTC, Romain-Ly commented on docs/en/integration/api/purchase_link_generation.md
> +The signature parameter is the same that example above.
Rajouter un paragraphe pour décrire comment faire une signature et faire un hyperlien ?

Sinon:
```
The signature parameter is the same as above.
The signature parameter is the same as the example above.
```
+ faire un hyperlien. Le above ne fonctionne plus si on intercale un truc plus tard.

2021-11-29 17:37 UTC, Romain-Ly commented on docs/en/integration/api/purchase_link_generation.md
> +## Purchase interruption
Abort purchase

2021-11-29 17:37 UTC, Romain-Ly commented on docs/en/integration/api/purchase_link_generation.md
> +For obvious reasons, a purchase whose state is completed or in progress cannot be interrupted (`OK` and some `PENDING` status). In this case you will receive a 409 http status code along with an expl
- C'est quoi cet endpoint ? Pour moi interruption, c'est pas la même chose que abort.  Dans le premier cas, tu peux reprendre. Dans le second cas c'est définitif. Utiliser `abort `ou `interrupt `partout.

- Enlever `For obvious reasons`, sauf is c'est vraiment obvious. IMO, Le PAYMENT_OK est obvious mais pas les pendings states.
- Décrire tous les états possible où on ne peut pas abort un purchase

2021-11-29 17:37 UTC, Romain-Ly commented on docs/en/integration/api/purchase_link_generation.md
> +If an interruption was possible, you will receive a 204 http code. The purchase status became `ABORTED`.
Faire un résumer des codes de retours dans un tableau et donner des exemples de la structure de donner aussi ?

2021-11-30 09:46 UTC, kmodry commented on docs/en/integration/api/purchase_link_generation.md
> +The signature parameter is describe as follow (example in python using jwt library):
En effet fail copié collé

2021-11-30 09:52 UTC, kmodry commented on docs/en/integration/api/purchase_link_generation.md
> +In case of error, this endpoint will return a 400 http code along with an explanation.
Il n'y en a pas du coup: c'est une 400 et du raw texte

2021-11-30 09:53 UTC, kmodry commented on docs/en/integration/api/purchase_link_generation.md
> +`https://back.ecard.pledg.co/api/purchase_status/?signature=<signature> GET`
En vrai j'ai copié du cas juste au dessus pour que ça ai du sens avec l'existant.

2021-11-30 09:55 UTC, kmodry commented on docs/en/integration/api/purchase_link_generation.md
> +This endpoint returns the following result:
Il y a pas une issue pour standardiser ? je prend par rapport au cas juste au dessus

2021-11-30 10:22 UTC, kmodry commented on docs/en/integration/api/purchase_link_generation.md
> +For obvious reasons, a purchase whose state is completed or in progress cannot be interrupted (`OK` and some `PENDING` status). In this case you will receive a 409 http status code along with an expl
- Ok
- Je suis assez peu d'accord, c'est vraiment évident, le paiement est activement en cours ou fait : on peut pas annuler. C'est logique non ?
- Pas d'accord, nos state ne regardent pas le merchant.

2021-11-30 10:24 UTC, kmodry commented on docs/en/integration/api/purchase_link_generation.md
> +`https://back.ecard.pledg.co/api/purchase_status/?signature=<signature> GET`
https://github.com/pledgcorporate/ecard-back/issues/5329

2021-11-30 10:24 UTC, kmodry commented on docs/en/integration/api/purchase_link_generation.md
> +This endpoint returns the following result:
https://github.com/pledgcorporate/ecard-back/issues/5329

2021-11-30 10:41 UTC, BafBar commented on docs/en/integration/api/purchase_link_generation.md
> +| `purchase_uid` | `string` | The reference of the purchase. |
The reference of the purchase. -> The purchase unique identifier. Détail mais comme reference existe aussi ca peut être confusing.

2021-11-30 10:41 UTC, BafBar commented on docs/en/integration/api/purchase_link_generation.md
> +In case of error, this endpoint will return a 400 http status code along with an explanation as raw text.
In case of an error, this endpoint will return a 400 http status code along with an explanation as raw text.

2021-11-30 10:41 UTC, BafBar commented on docs/en/integration/api/purchase_link_generation.md
> +For obvious reasons, a purchase whose state is completed or in progress cannot be aborted (`OK` and some `PENDING` status). In this case you will receive a 409 http status code along with an explanat
Not all purchase can be aborted:
- Purchases in state `OK` cannot be aborted. 
- Some purchases in state `PENDING`cannot be aborted.     

In this case you will receive a 409 http status code along with an explanation as raw text.

2021-11-30 10:41 UTC, BafBar commented on docs/en/integration/api/purchase_link_generation.md
> +If an interruption was possible, you will receive a 204 http code. The purchase status became `ABORTED`.
If the purchase was succesfully aborted, you will receive a 204 http code. The purchase status is changed to `ABORTED`.

2021-11-30 10:41 UTC, BafBar commented on docs/en/integration/api/purchase_link_generation.md
> +In case of error, this endpoint will return a 400 http status code along with an explanation as raw text.
In case of *an* error

2021-11-30 10:53 UTC, merged